# Generated by Django 2.1.4 on 2018-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigAutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('usernick', models.CharField(blank=True, db_column='UserNick', max_length=80, null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=100, null=True)),
                ('userlink', models.CharField(blank=True, db_column='UserLink', max_length=2047, null=True)),
                ('userfrom', models.CharField(blank=True, db_column='UserFrom', max_length=100, null=True)),
                ('userscor', models.DecimalField(blank=True, db_column='UserScor', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
